# This file is part of the Ulabox GearmanBundle.
# (c) Ivannis Suárez Jérez
#
gearman_bundle_async_event_handle:
    path: /async-event/handle
    methods:  [POST]
    defaults:
        _controller: ulabox_gearman.controller.event_async:handleAction
